### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/ComicsReader#1]
列出各階段應該實作的功能

# 1.0 版
- [ ] Collection 收藏功能 => 使用 Firebase 當 backend
- [ ] 把 `dm5` 包成 npm package
- [ ] 建立 api server，作為 universal app 的 api proxy server => 有些 request 需要夾帶 referrer 或 cookie
- [ ] Electron + Chrome Packaged App
- [ ] 搞一張 Google 能刷過的信用卡（如果用 `electron` release 就沒那麼必要了）

# 1.1 版
- [ ] 漫畫打包 zip 下載
  - [ ] 會不會用到 s3 呢
  - [ ] electron 或 chrome 應該有類似功能
- [ ] 打包成 firefox 和 safari 可用的套件
- [ ] 純 web 版

# 1.2 版
- [ ] 加入 [Ziltag](https://ziltag.com/) 圖片社群功能
- [ ] 搭一個留言系統
- [ ] Bitcoin 捐款之類（誤）

# 未排程
- [ ] 截圖儲存、單張儲存
- [ ] 梗圖收藏、管理
